version: '3.1'

services:
  db:
    image: mariadb:10.4
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo

  redis:
    image: redis:4.0
    ports:
      - "127.0.0.1:6379:6379"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    ports:
      - "127.0.0.1:9200:9200"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
